# Generated by Django 4.1 on 2023-05-02 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_ID", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_date", models.DateField()),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_ID", models.AutoField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                ("disease_ID", models.AutoField(primary_key=True, serialize=False)),
                ("disease_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("code", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Nurse",
            fields=[
                ("physician_ID", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "ssn",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("DOB", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Physician",
            fields=[
                ("physician_ID", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedEase.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                ("procedure_ID", models.AutoField(primary_key=True, serialize=False)),
                ("procedure_name", models.CharField(max_length=255)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("test_ID", models.AutoField(primary_key=True, serialize=False)),
                ("test_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("slot_ID", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("visit_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "appointment_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit",
                        to="MedEase.appointment",
                    ),
                ),
                (
                    "patient_ID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedEase.patient",
                    ),
                ),
                (
                    "prep_nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MedEase.nurse"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcedureAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedEase.physician",
                    ),
                ),
                (
                    "visit_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MedEase.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_ID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("dose", models.CharField(max_length=255)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedEase.medication",
                    ),
                ),
                (
                    "visit_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MedEase.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HaveTest",
            fields=[
                ("test_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nurse_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MedEase.nurse"
                    ),
                ),
                (
                    "visit_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MedEase.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedEase.disease",
                    ),
                ),
                (
                    "visit_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MedEase.visit"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="physician_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="MedEase.physician",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="MedEase.timeslot",
            ),
        ),
    ]
