# Generated by Django 4.1 on 2023-05-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_ID", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_date", models.DateField()),
                ("available", models.BooleanField(default=True)),
            ],
            options={"ordering": ["appointment_date", "time_slot__sequence"],},
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_ID", models.AutoField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                ("disease_ID", models.AutoField(primary_key=True, serialize=False)),
                ("disease_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HaveTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("code", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Nurse",
            fields=[
                ("physician_ID", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_ID", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("DOB", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Physician",
            fields=[
                ("physician_ID", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_ID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("dose", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                ("procedure_ID", models.AutoField(primary_key=True, serialize=False)),
                ("procedure_name", models.CharField(max_length=255)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ProcedureAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "ordering": ["appointment__appointment_date", "appointment__time_slot"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("test_ID", models.AutoField(primary_key=True, serialize=False)),
                ("test_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("slot_ID", models.AutoField(primary_key=True, serialize=False)),
                ("sequence", models.IntegerField(unique=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={"ordering": ["sequence"],},
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("visit_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "prep_nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MedEase.nurse"
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MedEase.registration",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "registration__appointment__appointment_date",
                    "registration__appointment__time_slot__sequence",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("start_time", "end_time"), name="unique_timeslot"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.appointment"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.patient"
            ),
        ),
        migrations.AddField(
            model_name="procedureassignment",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.physician"
            ),
        ),
        migrations.AddField(
            model_name="procedureassignment",
            name="procedure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.procedure"
            ),
        ),
        migrations.AddField(
            model_name="procedureassignment",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.visit"
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.medication"
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.visit"
            ),
        ),
        migrations.AddField(
            model_name="physician",
            name="department",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.department"
            ),
        ),
        migrations.AddConstraint(
            model_name="medication",
            constraint=models.UniqueConstraint(
                fields=("name", "brand"), name="unique_medication"
            ),
        ),
        migrations.AddField(
            model_name="havetest",
            name="nurse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.nurse"
            ),
        ),
        migrations.AddField(
            model_name="havetest",
            name="test",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="MedEase.test"
            ),
        ),
        migrations.AddField(
            model_name="havetest",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.visit"
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="disease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.disease"
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MedEase.visit"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="physician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="MedEase.physician",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="MedEase.timeslot",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("appointment_date", "time_slot", "physician"),
                name="unique_appointment",
            ),
        ),
    ]
