# Generated by Django 4.1 on 2023-05-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedEase", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nurse", options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="patient", options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddField(
            model_name="nurse",
            name="disambiguator",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AddField(
            model_name="patient",
            name="disambiguator",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AddField(
            model_name="physician",
            name="disambiguator",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AddConstraint(
            model_name="nurse",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"), name="unique_nurse"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_patient",
            ),
        ),
        migrations.AddConstraint(
            model_name="physician",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_physician",
            ),
        ),
    ]
