# Generated by Django 4.1 on 2023-05-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedEase", "0002_alter_nurse_options_alter_patient_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registration", name="unique_registration",
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("appointment",), name="unique_registration"
            ),
        ),
    ]
